config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/legal', to: 'pages#legal', as: 'legal'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  validates :content, length: { minimum: 10 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home legal]

  def home
  end

  def legal
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_cookies_banner.html.erb
<div id="cookiesBanner" class="cookies-banner py-3  d-none position-fixed w-100">
  <div class="d-md-flex container align-items-center">
    <p class="mb-md-0 flex-grow-1 text-white mr-md-3">
      Nous utilisons des cookies, dont des cookies tiers (Google) pour vous offrir une expérience utilisateur de qualité ainsi que pour suivre et analyser le trafic sur le site. En cliquant sur « Accepter », vous acceptez que nous utilisions ces cookies. Vous pouvez à tout moment modifier vos paramètres de cookies. Pour cela, nous vous invitons à consulter notre Politique de confidentialité en cliquant sur « Personnaliser »
      <br><%= link_to "En savoir plus", legal_path, target: "_blank", class: "link-no-decoration text-cookie" %>
    </p>
    <div class="d-flex">
      <div id="cookiesGlobalConsent" class="btn btn-cookie font-size-12px me-3">Accepter</div>
      <div class="btn btn-cookie font-size-12px" data-bs-toggle="modal" data-bs-target="#cookiesModal">Personnaliser</div>
    </div>
  </div>
</div>
<div class="modal fade font-size-14px font-montserrat" id="cookiesModal" tabindex="-1" role="dialog" aria-labelledby="cookiesModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered max-width-650px" role="document">
    <div class="modal-content p-3 ">
      <div class="modal-header border-0 p-0">
        <%= image_tag "logo.png", width: 60 %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body px-md-6">
        <p class="font-weight-bold title-small">Votre Accord sur l'utilisation des cookies</p>
        <p>Vous êtes libre d'activer et de désactiver à tout moment les familles de cookies suivantes :</p>
        <p class="font-weight-bold">Cookies strictement nécessaires</p>
        <div class="d-flex align-items-center justify-content-between mb-3">
          <p class="flex-grow-1 mb-0">Ils sont indispensables au bon fonctionnement du site.</p>
          <%= image_tag "check.svg", width: 25 %>
        </div>
        <p class="font-weight-bold">Cookies Statistiques</p>
        <div class="d-flex align-items-center mb-2">
          <p class="flex-grow-1 mb-0">Ils nous permettent d'établir des statistiques anonymes via Google Analytics</p>
          <div class="min-width-60px">
            <div class="toggle-slide-input">
              <input type="checkbox" name="google_analytics_consent" id="google_analytics_consent" data-analytics="<%= ENV['GOOGLE_ANALYTICS_KEY'] %>">
              <label for="google_analytics_consent"></label>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center">
        <div type="button" id="cookiesConfigBtn" class="btn btn-cookie" data-bs-dismiss="modal">Je valide</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%#= render "layouts/google_analytics" %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%#= meta_title %></title>
    <meta name="description" content="<%#= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%#= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%#= request.original_url %>" />
    <meta property="og:image" content="<%#= meta_image %>" />
    <meta property="og:description" content="<%#= meta_description %>" />
    <meta property="og:site_name" content="<%#= meta_title %>" />
    <%#= yield(:robots) %>
    <%#= csrf_meta_tags %>
    <%#= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- 	prevent Chrome animation on loading -->
    <script type="text/javascript"> </script>
  </head>
  <body>
    <%= render "layouts/cookies_banner" %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "yourdomain",
        "url": "https://www.yourdomain.com/",
        "logo": "",
        "contactPoint": [{
          "@type": "ContactPoint",
          "url": "https://www.yourdomain.com",
          "email": "contact@yourdomain.com",
          "telephone": "+33-30000000",
          "contactType": "customer service"
        }],
        "image": "",
        "description": ""
      }
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<%= content_for :meta_title, "Yourdomain - Your Meta" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1167355/pexels-photo-1167355.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
  <div class="container">
    <h1>Banner</h1>
  </div>
</div>

<div class="container page-min-height">
  <h2>Example btn Stripe</h2>
  <article> 
  <script async
  src="https://js.stripe.com/v3/buy-button.js">
</script>

<stripe-buy-button
  buy-button-id="buy_btn_1Mppv7KKtQnf8aE4fQqj2e0o"
  publishable-key="pk_test_51IUaE2KKtQnf8aE42pXFWBsteuriJNV5X3TzjLXkhQcwuzGUki2YYlorCXkjn4t5XtP2psmCr3Df5tBvRsp1ymFz00A1tQ6e80"
>
</stripe-buy-button>
   </article>
  <aside>  </aside>
</div>

app/views/pages/legal.html.erb
<% content_for(:robots) do %>
  <meta name="robots" content='noindex, nofollow'>
<% end %>

<div class="container page-min-height">
  <h1>Legal</h1>
  <div>
    À tout moment, l’Utilisateur peut faire le choix d’exprimer et de modifier ses souhaits en matière de Cookies. <a href=<%=ENV["DOMAIN_PROD"]%>><%=ENV["DOMAIN_PROD"]%>/</a> pourra en outre faire appel aux services de prestataires externes pour l’aider à recueillir et traiter les informations décrites dans cette section.</p>
    À tout moment, l’Utilisateur peut faire le choix d’exprimer et de modifier ses souhaits en matière de Cookies en cliquant sur le lien ci-dessous. <a href=<%=ENV["DOMAIN_PROD"]%>><%=ENV["DOMAIN_PROD"]%></a> pourra en outre faire appel aux services de prestataires externes pour l’aider à recueillir et traiter les informations décrites dans cette section.</p>
    <div class="d-flex justify-content-center mb-4">
      <div class="btn btn-cookie font-size-16px py-2" data-toggle="modal" data-target="#cookiesModal">PERSONNALISER LES COOKIES</div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button> 
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button> 
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-between align-items-center">
  <div class="footer-links">
  </div>
  <div class="footer-copyright d-flex flex-column">
    © 2023 <%=ENV["DOMAIN"] || "localhost:3000"%>
    <%= link_to legal_path do %>
      Mentions légales
    <% end %>
    <%= link_to "https://www.andyramaroson.com/", target: "_blank" do %>
      Site réalisé par Andy R.
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-perso">
  <!-- Logo -->
  <a href="/" class="navbar-perso-brand">
    <%= image_tag "logo.png" %>
  </a>
  <div class="d-none d-md-block">
    <div class="d-flex align-items-center justify-content-between">
      <%#= link_to "Home", "#", class: "navbar-perso-item navbar-perso-link" %>
      <%#= link_to "About me", "/", class: "navbar-perso-item navbar-perso-link" %>
      <%#= link_to "Contact", "/", class: "navbar-perso-item navbar-perso-link" %>
      <%#= link_to "Write", "/", class: "navbar-perso-item navbar-perso-link" %>
      <%# if user_signed_in? %>
        <%#= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, method: :delete , class: "navbar-perso-item navbar-perso-link"%>
        <%#= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar-large", alt: "avatar-large" %>
      <%#else %>
        <%#= link_to t(".sign_in", default: "Login"), new_user_session_path , class: "navbar-perso-item navbar-perso-link"%>
      <%# end %>
    </div>
  </div>

  <div class="d-block ">
    <div class="navbar-dropdown">
      <input id="toggle" type="checkbox"/>
      <label class="hamburger" for="toggle">
        <div class="top"></div>
        <div class="meat"></div>
        <div class="bottom"></div>
      </label>
      <div class="nav">
        <div class="nav-wrapper">
          <nav class= "d-flex flex-column">
            <%= link_to "Accueil", root_path, class: "navbar-link" %>
            <% if user_signed_in? %>
              <%= link_to "Se Déconnecter", destroy_user_session_path, class: "navbar-link", method: :delete %>
            <% else %>
              <%= link_to "Créer un Compte", new_user_registration_path, class: "navbar-link" %>
              <%= link_to "Se Connecter", new_user_session_path,  class: "navbar-link" %>
            <% end %>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<div style="height: 70px;"></div>